// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table ['transactions'] (schema:dynamic, payload:dynamic) 
.create-or-alter table ['transactions'] ingestion json mapping 'transactions_mapping'
```
[{"Properties":{"Path":"$['schema']"},"column":"schema","datatype":""},{"Properties":{"Path":"$['payload']"},"column":"payload","datatype":""}]
```
